[platformio]
default_envs = esp32s3

[common]
build_flags =
    -std=gnu++17
    -I ../../src
    -I ../../../embedded-bridge/cpp/include
    -DDOCTEST_CONFIG_SUPER_FAST_ASSERTS
    -DDOCTEST_CONFIG_NO_POSIX_SIGNALS
    -DDOCTEST_THREAD_LOCAL=
build_unflags = -std=gnu++11
lib_extra_dirs = ../../

[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.psram = disabled
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_upload.after_reset = watchdog-reset
build_flags =
    ${common.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags = ${common.build_unflags}
lib_extra_dirs = ${common.lib_extra_dirs}

[env:pico]

platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_flags = ${common.build_flags}
build_unflags = ${common.build_unflags}
lib_extra_dirs = ${common.lib_extra_dirs}
